secrets_service: bws #or whatever service is implemented. It uses the folder name of the service under secrets_backend
secrets_prefix: "ansible/"

bws_version: "1.0.0"
bws_install_path: "/usr/local/bin/bws"

bws_credentials: "{{ lookup('file', playbook_dir ~ '/../bws_credentials.yml') | from_yaml }}"

bws_project_id: "{{ bws_credentials.bws_project_id }}"
BWS_ACCESS_TOKEN: "{{ bws_credentials.bws_access_token }}"
