- name: "[stacks/dev/infra_config/jenkins] Ensure Jenkins home ownership"
  file:
    path: "{{ JENKINS_HOME_PATH }}"
    owner: 1000
    group: 1000
    recurse: yes

- name: "[stacks/dev/infra_config/jenkins] Ensure init.groovy.d exists"
  file:
    path: "{{ JENKINS_HOME_PATH }}/init.groovy.d"
    state: directory
    owner: 1000
    group: 1000


- name: "[stacks/dev/infra_config/jenkins] Set Jenkins URL via Groovy"
  copy:
    dest: "{{ JENKINS_HOME_PATH }}/init.groovy.d/01-set-url.groovy"
    content: |
      import jenkins.model.*
      def jlc = JenkinsLocationConfiguration.get()
      jlc.setUrl("{{ JENKINS_EXTERNAL_URL }}")
      jlc.save()

