- name: Configure dev stack
  include_tasks: "{{ role_path }}/../tasks/stack_setup.yml"
  vars:
    stack_name: "dev"

    stack_env_template: "dev.env.j2"
    stack_compose_template: "docker-compose.yml.j2"

    stack_data_dirs:
      - path: "{{ GITEA_DATA_PATH }}"
      - path: "{{ REGISTRY_SERVER_DATA }}"
      - path: "{{ JENKINS_HOME_PATH }}"
        owner: "1000"
        group: "1000"